### ISSUE TITLE
A bug may cause desktop icons invisible.

### ISSUE THREAD

**Issue by VergeDX** [yeyushengfan258/We10X-icon-theme#1]
I select the icon theme `We10X` in gnome tweak tool, then I reboot gnome-shell by using `Ctrl + F2, r command`, then I found that my desktop icons are invisible, and also cannot interact with them.
This bug did not disappear after reboot. There is no such problem when using other icon themes (like `Tela-pink`), there are icons on my desktop:
![image](https://user-images.githubusercontent.com/25173827/78618655-c780be00-78ad-11ea-837f-448304898471.png)

**Comment by VergeDX** [comment]
@yeyushengfan258

**Comment by yeyushengfan258** [comment]
这种情况我问了下别人,还没找到解决的办法,我其实不怎么用gnome,所以自己没研究过
