### ISSUE TITLE
Nice Steam icon~

### ISSUE THREAD

**Issue by yeyebbc** [yeyushengfan258/We10X-icon-theme#21]
I am the original creator of that Steam icon. 
And if you excuse me, it is not visually centred though.

No worries, just came to say hello, and good work this icon pack. I love it.

![image](https://user-images.githubusercontent.com/19569343/170540312-cd762acb-f1f3-468b-b69d-701256ec10d8.png)

**Comment by yeyushengfan258** [comment]
Thank you so much for your liking and for your hard work.
